### ISSUE TITLE
Chimp login could use $USER automatically

### ISSUE THREAD

**Issue by a1exsh** [zalando-techmonkeys/chimp#23]
Well, see $subj...

**Comment by szuecs** [comment]
Thanks for the request. I already thought about this, but it should be configurable, because not all people have the same UID local and as service user.

**Comment by a1exsh** [comment]
Totally, I just think a prompt like `Password for $USER` is going to make it clear, so such people will `^C` and run again with proper user argument.

**Comment by Raffo** [comment]
@a1exsh Yes, you could assume the user in case no user is provided. I could do that easily.
