### ISSUE TITLE
Force option doesn't seem to have effect

### ISSUE THREAD

**Issue by a1exsh** [zalando-techmonkeys/chimp#25]
After scaling up to 96 instances, I was trying to scale back down, but got this:

```sh
$ chimp scale my-app 24
GTH
Scale unsuccessful: App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'.
```

Adding `--force` didn't help: the same error message was displayed and scale down was not performed.

**Comment by Raffo** [comment]
Closed by #26
